version: '3'

services:
  cartmanager:
    build: ./CartManager
    ports:
      - "8083:8083"
    depends_on:
      - authentication
      
  producmanager:
    build: ./ProductManager
    ports:
      - "8082:8082"
    depends_on:
      - authentication

  authentication:
    build: ./Authentication
    ports:
      - "8081:8081"
    depends_on:
      - database

  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: sweetshop
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"